const musicals = [
  {
    id: 1,
    title: "next to normal",
    tags: ["tag10", "tag2", "tag3"],
    img_small: "./images/next-to-normal-small.png",
    img_medium: "./images/next-to-normal-medium.png",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi doloremque assumenda, suscipit officia id quaerat dolore consequatur nisi facilis laudantium blanditiis nesciunt nihil perspiciatis enim, ipsa iste a officiis velit unde earum voluptatibus veniam accusantium. Quibusdam iusto molestias tempora minus, nemo aliquam optio, labore ad harum quos beatae? Dolorum quaerat eveniet quae aspernatur facilis labore similique pariatur quos rerum repudiandae. Inventore illo at cum perferendis maiores eum et natus sapiente?",
  },
  {
    id: 2,
    title: "The Lion King",
    tags: ["tag1", "tag2", "tag3"],
    img_small: "./images/the-lion-king-small.png",
    img_medium: "./images/the-lion-king-medium.png",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla error quisquam, at ex soluta, cumque excepturi assumenda deleniti debitis perferendis non fugit aliquid recusandae quia commodi iste cum quasi pariatur voluptas veniam consequuntur culpa quod doloribus. Corporis fugit quibusdam voluptate aspernatur. Suscipit nostrum in inventore, consectetur adipisci voluptates dicta, quidem, libero molestias deleniti amet iste. Consequuntur iusto similique quibusdam doloremque?",
  },
  {
    id: 3,
    title: "Into The Woods",
    tags: ["tag1", "tag2", "tag3"],
    img_small: "./images/into-the-woods-small.png",
    img_medium: "./images/into-the-woods-medium.png",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi doloremque assumenda, suscipit officia id quaerat dolore consequatur nisi facilis laudantium blanditiis nesciunt nihil perspiciatis enim, ipsa iste a officiis velit unde earum voluptatibus veniam accusantium. Quibusdam iusto molestias tempora minus, nemo aliquam optio, labore ad harum quos beatae? Dolorum quaerat eveniet quae aspernatur facilis labore similique pariatur quos rerum repudiandae. Inventore illo at cum perferendis maiores eum et natus sapiente?",
  },
  {
    id: 4,
    title: "Company",
    tags: ["tag1", "tag2", "tag3"],
    img_small: "./images/company-small.png",
    img_medium: "./images/company-medium.png",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla error quisquam, at ex soluta, cumque excepturi assumenda deleniti debitis perferendis non fugit aliquid recusandae quia commodi iste cum quasi pariatur voluptas veniam consequuntur culpa quod doloribus. Corporis fugit quibusdam voluptate aspernatur. Suscipit nostrum in inventore, consectetur adipisci voluptates dicta, quidem, libero molestias deleniti amet iste. Consequuntur iusto similique quibusdam doloremque?",
  },
  {
    id: 5,
    title: "Dear Evan Hansen",
    tags: ["tag1", "tag2", "tag3"],
    img_small: "./images/dear-evan-hansen-small.png",
    img_medium: "./images/dear-evan-hansen-medium.png",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi doloremque assumenda, suscipit officia id quaerat dolore consequatur nisi facilis laudantium blanditiis nesciunt nihil perspiciatis enim, ipsa iste a officiis velit unde earum voluptatibus veniam accusantium. Quibusdam iusto molestias tempora minus, nemo aliquam optio, labore ad harum quos beatae? Dolorum quaerat eveniet quae aspernatur facilis labore similique pariatur quos rerum repudiandae. Inventore illo at cum perferendis maiores eum et natus sapiente?",
  },
  {
    id: 6,
    title: "Falsettos",
    tags: ["tag1", "tag2", "tag3"],
    img_small: "./images/falsettos-small.png",
    img_medium: "./images/falsettos-medium.png",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla error quisquam, at ex soluta, cumque excepturi assumenda deleniti debitis perferendis non fugit aliquid recusandae quia commodi iste cum quasi pariatur voluptas veniam consequuntur culpa quod doloribus. Corporis fugit quibusdam voluptate aspernatur. Suscipit nostrum in inventore, consectetur adipisci voluptates dicta, quidem, libero molestias deleniti amet iste. Consequuntur iusto similique quibusdam doloremque?",
  },
  {
    id: 7,
    title: "Matilda",
    tags: ["tag1", "tag2", "tag3"],
    img_small: "./images/matilda-small.png",
    img_medium: "./images/matilda-medium.png",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi doloremque assumenda, suscipit officia id quaerat dolore consequatur nisi facilis laudantium blanditiis nesciunt nihil perspiciatis enim, ipsa iste a officiis velit unde earum voluptatibus veniam accusantium. Quibusdam iusto molestias tempora minus, nemo aliquam optio, labore ad harum quos beatae? Dolorum quaerat eveniet quae aspernatur facilis labore similique pariatur quos rerum repudiandae. Inventore illo at cum perferendis maiores eum et natus sapiente?",
  },
  {
    id: 8,
    title: "Sunday In The Park With George",
    tags: ["tag1", "tag2", "tag3"],
    img_small: "./images/sunday-in-the-park-with-george-small.png",
    img_medium: "./images/sunday-in-the-park-with-george-medium.png",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla error quisquam, at ex soluta, cumque excepturi assumenda deleniti debitis perferendis non fugit aliquid recusandae quia commodi iste cum quasi pariatur voluptas veniam consequuntur culpa quod doloribus. Corporis fugit quibusdam voluptate aspernatur. Suscipit nostrum in inventore, consectetur adipisci voluptates dicta, quidem, libero molestias deleniti amet iste. Consequuntur iusto similique quibusdam doloremque?",
  },
];

export default musicals;
